version: '2.0'
services:
  syslog-some-app-using-syslog:
    image: tob123/rsyslog
    build: ./
    user: root
    environment:
      - ENABLE_LOGLOCAL=on
      - ENABLE_TOKAFKA=off
      - ENABLE_REMOTE_SYSLOG=on
      - SYSLOG_PORT=514
  syslog-producer:
    image: tob123/rsyslog
    build: ./
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
